#! /usr/bin/env bash
for proto_file in $(find "./proto/" -name "*.proto"); do
  protoc -I proto --grpc-gateway_out ./pb \
    --grpc-gateway_opt logtostderr=true \
    --grpc-gateway_opt paths=source_relative \
    --proto_path=./proto \
    --go_out=./pb --go_opt=paths=source_relative \
    --go-grpc_out=./pb --go-grpc_opt=paths=source_relative \
    --swagger_out=./swaggers \
    --swagger_opt=logtostderr=true \
    "$proto_file"
done
